### ISSUE TITLE
Services not picked up

### ISSUE THREAD

**Issue by thdxr** [madwire/tutum-nginx-proxy#7]
I've followed the instructions and created a service running on internal port 80 with VIRTUAL_HOST set - however nginx-proxy is not able to pick it up.  Do you have any idea what could be wrong?

**Comment by madwire** [comment]
Hi Dax, Hmmm, not sure what you are doing wrong.

_Make sure if you are using the tutum dashboard that you click on "Click to override ports defined in image"_

<img width="810" alt="screen shot 2015-09-25 at 21 14 14" src="https://cloud.githubusercontent.com/assets/99309/10111280/d3f44f1e-63ca-11e5-88ef-cf5672e2bfb5.png">

_and it looks like this:_

<img width="686" alt="screen shot 2015-09-25 at 21 20 03" src="https://cloud.githubusercontent.com/assets/99309/10111340/4334fc66-63cb-11e5-8ac8-08249b3808f4.png">

_Again if you are using the tutum dashboard, make sure that the nginx container has API Access like this:_

<img width="925" alt="screen shot 2015-09-25 at 21 16 04" src="https://cloud.githubusercontent.com/assets/99309/10111382/8a5ba0a4-63cb-11e5-99b6-7acf074bd226.png">

_If you are using stacks your nginx stack should be like:_

``` yml
nginx:
  image: 'madwire/tutum-nginx-proxy:latest'
  ports:
    - '80:80'
  restart: always
  roles:
    - global
```

_and your website like:_

``` yml
website:
  image: 'my-image'
  environment:
    - VIRTUAL_HOST=www.example.com
  expose:
    - '80'
```
